version: '3.7'

services:
  bot:
    restart: always
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ENV=${ENV}
      - VER=${VER}
      - TZ=${TZ}
    volumes:
      - ../data:/home/app/data

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
