version: '3.7'

services:
  bot:
    restart: always
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - ENV=${ENV}
      - VER=${VER}
      - TZ=${TZ}
    volumes:
      - ../data:/home/app/data
    networks:
      - polybot

networks:
  polybot:
    name: polybot-${ENV}
    driver: bridge
    external: true
