version: '3.7'

services:
  bot:
    restart: always
    build:
      dockerfile: ./Dockerfile
    environment:
      - ENV=${ENV}
      - VER=${VER}
      - TZ=${TZ}
      - SENTRY_DSN=${SENTRY_DSN}
      - BOT_TOKEN=${BOT_TOKEN}
      - POLYBOT_PORT=${POLYBOT_PORT}
      - POLYBOT_API_PORT=${POLYBOT_API_PORT}
      - IMAGE_GEN_PORT=${IMAGE_GEN_PORT}
    volumes:
      - ../../data:/home/app/data

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
