FROM rocm/pytorch:latest

# Patch: Change jenkins uid to be compatible
RUN usermod -u 1005 jenkins

# Create app user and add to video & render group
RUN useradd app -ms /bin/bash --uid 1000 && \
	usermod -a -G video,render app
